





var paginationString = $(".pagination .ddc-pagination-current-page").parent().html().split(" ");

var paginationLength = paginationString.length;

var p = paginationString[paginationLength-1];

console.log(p);



var $div = $('<div>');

$div.load('index.php #somediv', function(){
    // now $(this) contains #somediv
});



?start=16&

jQuery(this.destTarget[this.index]).load(this.protocal + '//' + this.tld + this.vlp + this.searchParam + this.stockNumbersString + this.dataTarget[this.index]);


[16, 32, 48 ]


+ this.pagination

var content;

$.get(this.protocal + '//' + this.tld + this.vlp + this.searchParam + this.stockNumbersString, function(data){
    content= data;
});
// Do something with content:
console.log(content);

https://www.mapleridgechrysler.com/all-inventory/index.htm?search=ZT758311+OR+ZC347004+OR+ZC105339+OR+ST101677+OR+ST183492+OR+ST193327+OR+PA815888+OR+PA727101+OR+PA727044+OR+PA727056


var content;

$.get('https://www.mapleridgechrysler.com/all-inventory/index.htm?search=ZT758311+OR+ZC347004+OR+ZC105339+OR+ST101677+OR+ST183492+OR+ST193327+OR+PA815888+OR+PA727101+OR+PA727044+OR+PA727056', function(data){
    content= data;
});
// Do something with content:
console.log(content);


$.get(this.protocal + '//' + this.tld + this.vlp + this.searchParam + this.stockNumbersString, function(data){
    
    var targetDiv = $(data).find('.ddc-content.inventory-listing-default .bd').html();
    
  console.log("Data: " + targetDiv);
});




$.get("logFile", function(response) {
     var logfile = response;
});

var stuff;
$.get('logFile', function (response) {
    stuff = response;
});



// Assign handlers immediately after making the request,
// and remember the jqxhr object for this request
var jqxhr = $.get( "example.php", function() {
  alert( "success" );
})
  .done(function() {
    alert( "second success" );
  })
  .fail(function() {
    alert( "error" );
  })
  .always(function() {
    alert( "finished" );
  });
 
// Perform other work here ...
 
// Set another completion function for the request above
jqxhr.always(function() {
  alert( "second finished" );
});





var urls = ['/url/one','/url/two', ....];

$.each(urls, function(i,u){ 
     $.ajax(u, 
       { type: 'POST',
         data: {
            answer_service: answer,
            expertise_service: expertise,
            email_service: email,
         },
         success: function (data) {
             $(".error_msg").text(data);
         } 
       }
     );
});
//Note: The messages generated by the success callback will overwrite each other as shown. You'll probably want to use $('#someDiv').append() or similar in the success function.





jQuery.ajax({
			url: this.protocal + '//' + this.tld + this.vlp + this.searchParam + this.stockNumbersString + this.pagination,
			success: function (data) {

				if (data != "") {
					loading = false;
					
					var hostPageContainer = this.dataTarget[this.index];
					
					jQuery(hostPageContainer, data).each(function (index) {



					});
				}
			}
		});








var myStrArray = ["http://www.google.de", "http://www.facebook.de", "http://www.lycos.de"];

//Initialize local deferred for myStrArray 
var myDeferredArray = [];
for (var i = 0; i < myStrArray; i++)
{
   myDeferredArray[i] = $.Deferred();
}

for (var i = 0; i < myStrArray.length; i++)
{
   $(element).load(myStrArray, function() {
       doSomething();
       myDeferredArray[i].resolve();
   });
}

return myDeferredArray as single deferred


$.when.apply(null, deferreds);

